# Generated by Django 3.2.7 on 2021-10-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
